# Generated by Django 5.1.2 on 2024-11-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank="True",
                max_length=400,
                null="True",
                verbose_name="Ссылка на оплату",
            ),
            preserve_default="True",
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank="True", max_length=255, null="True", verbose_name="ID сессии"
            ),
            preserve_default="True",
        ),
        migrations.AddField(
            model_name="payments",
            name="status",
            field=models.CharField(
                blank="True", max_length=50, null="True", verbose_name="Статус платежа"
            ),
            preserve_default="True",
        ),
    ]
