# Generated by Django 5.1.2 on 2024-11-17 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments_link_payments_session_id_payments_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="method",
            field=models.CharField(
                blank="True",
                choices=[("CASH", "Оплата наличными"), ("ONLINE", "Перевод на счет")],
                default="Перевод на счет",
                max_length=50,
                null="True",
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="user",
            field=models.ForeignKey(
                blank="True",
                null="True",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
