# Generated by Django 5.1.2 on 2024-10-22 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название курса"),
                ),
                (
                    "description",
                    models.TextField(
                        blank="True", null="True", verbose_name="Описание курса"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank="True",
                        null="True",
                        upload_to="courses/",
                        verbose_name="Изображение курса",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank="True",
                        max_length=100,
                        null="True",
                        verbose_name="Название урока",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank="True", null="True", verbose_name="Описание урока"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank="True",
                        null="True",
                        upload_to="lessons/",
                        verbose_name="Изображение урока",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank="True", null="True", verbose_name="Ссылка на видео"
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["name"],
            },
        ),
    ]
