# Generated by Django 5.1.2 on 2024-10-22 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank="True",
                null="True",
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название урока"),
        ),
    ]
