# Generated by Django 5.1.2 on 2024-10-25 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_remove_course_is_active_remove_lesson_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank="True",
                null="True",
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_set",
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
    ]
